apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - migration-job.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
